### ISSUE TITLE
Flowtoys Protocol

### ISSUE THREAD

**Issue by noerw** [benkuper/FlowtoysConnectBridge#1]
Hi,
I'm investigating to implement a remote control for the podpoi v2.
You seem to be the person that could tell me: Is the protocol the capsule / Connect is speaking documented somewhere?

~Norwin

**Comment by benkuper** [comment]
Hey, sorry for the late answer.
Yes the protocol is in this repo in the repo, here : https://github.com/benkuper/FlowtoysConnectBridge/blob/master/RFGroup.h
It's not documented but if you code a bit you should understand it pretty fast.

Also note that the protocol is changing very soon so you should wait for the next version to avoid having to do it all over again.
The goal of the bridge is to make it easy to control it from Serial or OSC instead of the RF system. As soon as there is a stable version out, there will be a documentation of how to use it.

**Comment by noerw** [comment]
Hej, thanks for the answer, will look into it!
Will the new version be distributed as a firmware update to existing products, or does it only apply to new devices?

**Comment by benkuper** [comment]
It should be a firmware update yes
